name: Build Mod

on: [ push, pull_request ]

jobs:
  buildJar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.7
      - name: Setup Path
        run: |
          echo "${ANDROID_HOME}/build-tools/34.0.0" >> $GITHUB_PATH
      - name: Setup Java JDK 17
        uses: actions/setup-java@v4.2.2
        with:
          java-version: 17
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build mod jar
        run: ./gradlew deploy
      - name: Upload a Build jar file
        uses: actions/upload-artifact@v4.3.6
        with:
          name: ${{ github.event.repository.name }}
          path: build/libs/${{ github.event.repository.name }}.jar
